Karudev\PersonBundle\Entity\Person:

    properties:

        gender:
            - Choice:
                choices:  [M, F]
                message:  Choose a valid gender.
        firstname:

            - Length:
                min: 2
                max: 50
                minMessage: The firstname must contain at least 2 letter
                maxMessage: The firstname must be maximum 50 letter
        lastname:

           - Length:
                min: 2
                max: 50
                minMessage: The lastname must contain at least 50 letter
                maxMessage: The lastname must be maximum 50 letter
        email:
            - Email:
                message: The email "{{ value }}" is not a valid email.
        mainPhone:
#            - Type:
#                type: numeric
#                message: The value "{{ value }}" is not a valid "{{ type }}".
            - Length:
                min: 10
        secondaryPhone:
#            - Type:
#                type: numeric
#                message: The value "{{ value }}" is not a valid "{{ type }}".
            - Length:
                min: 10
#        address:
#        addressComplement:
#        zipCode:
#        city:
#        district:
#        country:
#        birthday:




