app:
    resource: '@AppBundle/Controller/'
    type: annotation

karudev_person:
    resource: "@KarudevPersonBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"