<?php

namespace Karudev\PersonBundle\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasePersonRepository extends \Doctrine\ORM\EntityRepository
{
}
